### ISSUE TITLE
前に作ったイベントを元に新イベント作りたい

### ISSUE THREAD

**Issue by wasabi315** [traPtitech/knoQ-UI#396]

**Comment by fuji8** [comment]
一からイベントを作るのが面倒で、前に作ったイベントの情報を予めフォームに入れたい

**Comment by wasabi315** [comment]
## 仕様
- `pages/EventNew.vue`を編集して，以前に作ったイベント情報を予めフォームに入れられるようにする．
- クエリパラメータにイベントのIDを含めることで，元となるイベントを決められるようにする．
  - 例: `/events/new?baseID=情報元のイベントID`

## 実装方法
- `event-form-base`コンポーネントのプロパティにイベント情報を渡せば，フォームは勝手に埋まってくれる．
- `pages/EventEdit.vue`を参考にすればよい(ほぼ同じような感じになるはず)
