### ISSUE TITLE
複数の日にまたがるイベントの作成

### ISSUE THREAD

**Issue by itt828** [traPtitech/knoQ-UI#936]
- 実装する前に、今まで1日のイベントしか作れないように実装されていた(フォームで日と時を分けて、POSTする時に結合している)理由を確認する
- バックエンドは複数の日にまたがるイベントを受けとれるようになっている

**Comment by wasabi315** [comment]
（あまりはっきりと覚えていないですが...）
1日のイベントしか作れないように実装されていたのはイベントが複数の部屋を持てないからだったと思います．日をまたぐイベントを作成する時にはそれぞれの日で使用する部屋を選べる必要が出てきます．
https://github.com/traPtitech/knoQ/issues/174

**Comment by itt828** [comment]
その他で開催のほうは日をまたいでもサーバー側の問題はなさそうということで、その他で開催だけ開催/終了日を増やしてみる方向ですすめてください:pray:

思ったこと: ほとんどのイベントは一日の開催なので、開催日を入力したときに終了日が同じ日付で自動入力されるみたいな実装だといいかも

**Comment by itt828** [comment]
#937
